// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/yigalziskand/dev/go/src/github.com/ziskandyigal/stringculator/converter/converter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConverter is a mock of Converter interface.
type MockConverter struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder struct {
	mock *MockConverter
}

// NewMockConverter creates a new mock instance.
func NewMockConverter(ctrl *gomock.Controller) *MockConverter {
	mock := &MockConverter{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter) EXPECT() *MockConverterMockRecorder {
	return m.recorder
}

// ToMD5 mocks base method.
func (m *MockConverter) ToMD5(num int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToMD5", num)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToMD5 indicates an expected call of ToMD5.
func (mr *MockConverterMockRecorder) ToMD5(num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToMD5", reflect.TypeOf((*MockConverter)(nil).ToMD5), num)
}

// ToSHA1 mocks base method.
func (m *MockConverter) ToSHA1(num int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSHA1", num)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToSHA1 indicates an expected call of ToSHA1.
func (mr *MockConverterMockRecorder) ToSHA1(num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSHA1", reflect.TypeOf((*MockConverter)(nil).ToSHA1), num)
}

// ToSHA256 mocks base method.
func (m *MockConverter) ToSHA256(num int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSHA256", num)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToSHA256 indicates an expected call of ToSHA256.
func (mr *MockConverterMockRecorder) ToSHA256(num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSHA256", reflect.TypeOf((*MockConverter)(nil).ToSHA256), num)
}
